-- InsuranceClaims Table
CREATE TABLE InsuranceClaims (
    CLAIM_ID NUMBER PRIMARY KEY,
    POLICY_NUMBER VARCHAR2(50),
    CLAIM_DATE DATE,
    CLAIM_AMOUNT NUMBER,
    STATUS VARCHAR2(50)
);

-- ClaimProcessings Table
CREATE TABLE ClaimProcessings (
    PROCESSING_ID NUMBER PRIMARY KEY,
    CLAIM_ID NUMBER REFERENCES InsuranceClaims(CLAIM_ID),
    PROCESSING_DATE DATE,
    PROCESSING_NOTES VARCHAR2(255),
    PROCESSING_STATUS VARCHAR2(50)
);

-- ClaimsReports Table
CREATE TABLE ClaimsReports (
    REPORT_ID NUMBER PRIMARY KEY,
    REPORT_DATE DATE,
    TOTAL_CLAIMS NUMBER,
    AVERAGE_CLAIM_AMOUNT NUMBER,
    CLAIMS_STATUS_BREAKDOWN CLOB
);